pipeline {
    agent any

    tools {
        maven 'Maven 3.6.3'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Anshika2203/maven-template-repository.git', branch: 'master'
            }
        }

        stage('Initialize') {
            steps {
                script {
                    class SimpleMavenBuild implements Serializable {
                        def steps

                        SimpleMavenBuild(steps) { this.steps = steps }

                        def mavenBuild(String buildFile, String buildTarget) {
                            steps.echo "Validating Build Parameters"

                            if (checkMandatoryFields(buildFile)) {
                                def mavenCommand = "mvn -f ${buildFile} ${buildTarget ?: 'install'}"
                                steps.sh "cd ${steps.pwd()}; ${mavenCommand}"
                            } else {
                                steps.error "Build parameter validation failed."
                            }
                        }

                        def checkMandatoryFields(def field) {
                            if (field == null || field.trim().isEmpty()) {
                                steps.echo "Build file parameter is blank"
                                return false
                            }
                            return true
                        }
                    }

                    def buildTool = new SimpleMavenBuild(this)
                    buildTool.mavenBuild('pom.xml', 'install')
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
        }
    }
}
