def SimpleMavenBuild

pipeline {
    agent any

    tools {
        maven 'MavenV3.9.7'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Anshika2203/maven-template-repository.git', branch: 'master'
            }
        }

        stage('Initialize') {
            steps {
                script {
                    buildScript = load "templates/MavenBuild/SimpleMavenBuild.groovy"
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Instantiate the SimpleMavenBuild class and call the mavenBuild method
                    def buildTool = buildScript.SimpleMavenBuild(this)
                    buildTool.mavenBuild('pom.xml', 'install')
                }
            }
        }
    }

    post {
        always {
            // Archive the build artifacts
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            // Optionally, you can add steps here to notify on build status, clean up, etc.
        }
    }
}